### ISSUE TITLE
What kind of git tag bumpversion uses?

### ISSUE THREAD

**Issue by GreatBahram** [c4urself/bump2version#109]
Hello there,

I think it is necessary to mention that you are using `Lightweight` tags in git. I couldn't find this information either in the document `README.md` or in the source code documentation. The only way to figure out is to read the source code!

Thanks,

**Comment by ekohl** [comment]
It depends on how you configure it. Without a message it is lightweight but you can pass in a message. That's required for signed tags since that's what git requires.

It looks like `--tag-message` is not documented in README.md so a PR to update it would be highly welcome. `--help` will show the option.

**Comment by GreatBahram** [comment]
Yeah, that is true! You could pass an **optional** message to this function and it will use `git tag -m` which results in an `annotated` one. I think this function's doc-string should be updated as well:
https://github.com/c4urself/bump2version/blob/527ca7af0f8cdc80fee7cbb0392855ee2561958a/bumpversion/vcs.py#L128
