### ISSUE TITLE
Adding @florisla as a collaborator

### ISSUE THREAD

**Issue by ekohl** [c4urself/bump2version#116]
Splitting this off from https://github.com/c4urself/bump2version/issues/86#issuecomment-571155739

AFAIK we have no formal process to add people since it hasn't been needed so far. That's why I think an issue here should be good enough.

@florisla has clearly shown an interest in the project. Not only by providing PRs, but also by commenting on issues and PRs of others. I'm also happy with his general approach and the quality of this work. This should be recognized and rewarded since IMHO the project will greatly benefit from it.

AFAIK @c4urself is the only one who can manage permissions so directly CCing here.

**Comment by florisla** [comment]
I don´t need commit permission in master, but I'd love to be able to add labels to issues and PRs.

**Comment by c4urself** [comment]
agree fully, turns out I did send the invite @florisla -- now resent!

**Comment by c4urself** [comment]
@florisla @ekohl -- it may be a good idea to start a chat among collaborators to discuss things more quickly, not sure how you feel about that? I'm pretty active with Bazel and since Google pays for that Slack we could just join a free channel there: https://slack.bazel.build/ -- #bump2version channel -- this would give me more visibility as I don't typically look at GitHub emails very regularly.

**Comment by florisla** [comment]
Thanks, the label thing works :-)

I just joined that slack, so chatting there is fine for me.

**Comment by ekohl** [comment]
@florisla welcome to the team!

@c4urself Out of principle I don't connect to slack since I'm opposed to proprietary communication systems.

**Comment by c4urself** [comment]
@ekohl -- understood. any other suggestions? (IRC, Zulip ... ?)

**Comment by ekohl** [comment]
I'm on IRC already so that would be easy for me. Don't know about others.
