### ISSUE TITLE
Quotation marks matter

### ISSUE THREAD

**Issue by wagenrace** [c4urself/bump2version#76]
I had `version="0.2.0"` in my setup.py but when updating using bump2version patch it made `version="version='0.2.0'"`
Changing it to `version='0.2.0'` did solve the problem for now

**Comment by florisla** [comment]
Can you share your bumpversion configuration? That makes it easier for us to investigate.

**Comment by wagenrace** [comment]
OS: Windows 10 64bit
Python: 3.7.3
bump2version: 0.5.10

**Comment by florisla** [comment]
Could you post the content of your `bumpversion.cfg` (or `setup.cfg`) file?

**Comment by wagenrace** [comment]
My setup.cfg of the package I try to bump the version of looks like this:
`[bumpversion]
current_version = 0.2.0
commit = True
tag = True

[bumpversion:file:setup.py]
search = version='{current_version}'
replace = version='{new_version}'

[bumpversion:file:tomni/__init__.py]
search = __version__ = '{current_version}'
replace = __version__ = '{new_version}'

[bdist_wheel]
universal = 1

[flake8]
exclude = docs

[aliases]
test = pytest

[tool:pytest]
collect_ignore = ['setup.py']

[coverage:report]
omit = 
	*/test_*.py
	*/__init__.py
	*/integration*.py
	setup.py
`

**Comment by wagenrace** [comment]
My setup.cfg of the package I try to bump the version of looks like this:
```
[bumpversion]
current_version = 0.2.0
commit = True
tag = True

[bumpversion:file:setup.py]
search = version='{current_version}'
replace = version='{new_version}'

[bumpversion:file:tomni/__init__.py]
search = __version__ = '{current_version}'
replace = __version__ = '{new_version}'

[bdist_wheel]
universal = 1

[flake8]
exclude = docs

[aliases]
test = pytest

[tool:pytest]
collect_ignore = ['setup.py']

[coverage:report]
omit = 
	*/test_*.py
	*/__init__.py
	*/integration*.py
	setup.py
```

**Comment by florisla** [comment]
You are right that quotation marks matter.

But that's fine -- you may *want* it to match either single or double quotes, but not the other.

The problem is that supporting both quotation styles at the same time is hard to do -- `search` does not accept regular expressions.

I remember I've worked around this in the past, but I can't seem to reproduce this at the moment.
I probably included the quotation marks in the `parse` string in some way.

{{{
[bumpversion:file:setup.py]
parse = version\s*=\s*['"](?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)['"]
}}}

For the record, here's what's causing the weird result:

Your `setup.py` contained double quotes `version="0.2.0"` but your `search` was looking for single quotes `version='{current_version}'`.  Consequently, the search pattern did not match.  (Unfortunately, this failure happens silently, even in verbose mode)

In that case, Bump2version (silently) falls back to the default search, using the serialize pattern (in this case the default `{major}.{minor}.{patch}`).  This resulted in a match on `0.2.0` in the string `version="0.2.0"`.

It replaces the *match* with the new version, which you defined in `replace = version='{new_version}'`.

So `version="0.2.0"` becomes `version="version='0.2.1'"`.

**Comment by wagenrace** [comment]
That is indeed the behavior I saw. Thanks for looking in to it. I will just work around by using only single quotes (for some reason my version was the only double quote string in setup.py)

**Comment by schuderer** [comment]
Thanks for the explanation! I'm leaving this comment as a heads-up for users using the excellent [black formatter](python/black), which changes single quotes into double quotes. So if you're a user of `black`, you probably need to change the search/replace patterns in your `bumpversion.cfg` (or `setup.cfg`) from `'` to `"`.

**Comment by aldoea** [comment]
I had a similar problem with the quotation marks on the global var __version__ declared on my __init__.py package so I just left it as this:

```python 
bumpversion:file:mypack/__init__.py]
search = "{current_version}"
replace = "{new_version}"
```

I'm not planning to add more content to this file so I hope not have future problem with this approach.
